package com.mycompany.aplikasii;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RIFQI
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class MainFrame extends javax.swing.JFrame {
    
    public MainFrame() {
        initComponents();
        loadBarangFromFile(); // Load data from file when the application starts
        updateTable();
    }
    
    private ArrayList<Barang> barangList = new ArrayList<>();
    private DefaultTableModel model;
    private static final String FILE_NAME = "barang.txt"; // Nama file untuk menyimpan data

    
    /**
     * Creates new form Input
     */
   
    

    public void simpanKeFile() {
        try (BufferedWriter writer = new  BufferedWriter(new FileWriter(FILE_NAME, true))) {
            writer.write(this.toString());
            writer.newLine();
            System.out.println("Data barang berhasil disimpan.");
            loadBarangFromFile();
        } catch (IOException e) {
            System.out.println("Terjadi kesalahan saat menyimpan data: " + e.getMessage());
        }
    }

    // Metode untuk membaca data barang dari file
    public static void bacaDariFile() {
        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_NAME))) {
            String line;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
            }
        } catch (IOException e) {
            System.out.println("Terjadi kesalahan saat membaca data: " + e.getMessage());
        }
    }
    

    private void loadBarangFromFile() {
        try (BufferedReader br = new BufferedReader(new FileReader("barang.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(" \\| ");
//                if (data.length == 3) {
                    String kode = data[0];
                    String jenis = data[1];
                    String lokasi = data[2];
                    barangList.add(new Barang(kode, jenis, lokasi));
//                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
        
    private void saveBarangToFile() {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("barang.txt"))) {
            for (Barang barang : barangList) {
                bw.write(barang.getKode() + " | " + barang.getJenis() + " | " + barang.getLokasi());
                bw.newLine(); 
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
         
    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) tbHasil.getModel();
        model.setRowCount(0); // Clear the table
        for (Barang barang : barangList) {
            model.addRow(new Object[]{barang.getKode(), barang.getJenis(), barang.getLokasi()});
        }
    }
           


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJenis = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        cmbLok = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHasil = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        urtkn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INPUT BARANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("KODE PO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("JENIS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("LOKASI");

        cmbLok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- PILIH -", "GUDANG BANDUNG", "GUDANG JAKARTA", "GUDANG SUMATRA" }));
        cmbLok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLokActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("PENCARIAN");

        tbHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode PO", "Jenis", "Lokasi"
            }
        ));
        jScrollPane1.setViewportView(tbHasil);

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        cari.setText("CARI");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        urtkn.setText("URUTKAN");
        urtkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urtknActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbLok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(simpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ubah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hapus))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urtkn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbLok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(hapus)
                    .addComponent(ubah))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari)
                    .addComponent(urtkn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        String kode = txtKode.getText();
        String jenis = txtJenis.getText();
        String lokasi = cmbLok.getSelectedItem().toString();
        Barang barang = new Barang(kode, jenis, lokasi);
        barangList.add(barang);
        saveBarangToFile(); // Save data to file after adding
        updateTable();
        clearFields();
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        int selectedRow = tbHasil.getSelectedRow(); // Pastikan tbHasil adalah nama tabel Anda
        if (selectedRow >= 0) {
            String kode = txtKode.getText();
            String jenis = txtJenis.getText();
            String lokasi = cmbLok.getSelectedItem().toString(); // Menggunakan getSelectedItem() bukan getSelectedItems()

            // Update the barang in the list
            Barang updatedBarang = new Barang(kode, jenis, lokasi);
            barangList.set(selectedRow, updatedBarang);

            // Save updated list to file
            saveBarangToFile(); // Save data to file after updating
            updateTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih barang yang ingin diubah.");
        }
    }

    private void clearFields() {
        txtKode.setText("");
        txtJenis.setText("");
        cmbLok.setSelectedIndex(0); // Pastikan 'lokasi' adalah nama JComboBox Anda
    }

    public void running() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
            int selectedRow = tbHasil.getSelectedRow(); // Get the selected row index
    if (selectedRow >= 0) {
        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus barang ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Remove the selected item from the list
            barangList.remove(selectedRow);
            // Save updated list to file
            saveBarangToFile(); 
            // Update the table view
            updateTable(); 
        }
    } else {
        JOptionPane.showMessageDialog(this, "Silakan pilih barang yang ingin dihapus.");
    }

    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        String searchTerm = txtSearch.getText().toLowerCase(); // Ambil istilah pencarian
    ArrayList<Barang> filteredList = new ArrayList<>();

    for (Barang barang : barangList) {
        if (barang.getKode().toLowerCase().contains(searchTerm) || 
            barang.getJenis().toLowerCase().contains(searchTerm) || 
            barang.getLokasi().toLowerCase().contains(searchTerm)) {
            filteredList.add(barang); // Tambahkan item yang cocok ke daftar yang difilter
        }
    }

    // Perbarui tabel dengan daftar yang difilter
    DefaultTableModel model = (DefaultTableModel) tbHasil.getModel();
    model.setRowCount(0); // Kosongkan tabel
    for (Barang barang : filteredList) {
        model.addRow(new Object[]{barang.getKode(), barang.getJenis(), barang.getLokasi()});
    }
    }//GEN-LAST:event_cariActionPerformed

    private void urtknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urtknActionPerformed
        // TODO add your handling code here:
        Collections.sort(barangList, new Comparator<Barang>() {
        @Override
        public int compare(Barang b1, Barang b2) {
            return b1.getKode().compareTo(b2.getKode()); // Urutkan berdasarkan Kode PO
        }
    });
    saveBarangToFile(); // Simpan daftar yang sudah diurutkan ke file
    updateTable(); // Perbarui tampilan tabel
    }//GEN-LAST:event_urtknActionPerformed

    private void cmbLokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLokActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cmbLok;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tbHasil;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JButton ubah;
    private javax.swing.JButton urtkn;
    // End of variables declaration//GEN-END:variables
}

