/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aplikasipenerimaansiswabaru;

/**
 *
 * @author RIFQI
 */

import java.io.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

public class Aplikasi extends javax.swing.JFrame {

    ArrayList<Siswa1379> daftarSiswa1379 = new ArrayList<>();
    DefaultTableModel tableModel;

    /**
     * Creates new form Aplikasi
     */
    
    int indexEdit1379 = -1;

    public Aplikasi() {
        initComponents();
        tbl1379.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tbl1379.getSelectedRow();
                if (row >= 0) {
                    nama1379.setText((String) tableModel.getValueAt(row, 0));
                    nisn1379.setText((String) tableModel.getValueAt(row, 1));
                    asel1379.setText((String) tableModel.getValueAt(row, 2));
                    nilai1379.setText(tableModel.getValueAt(row, 3).toString());
                    indexEdit1379 = row; // Simpan baris yang sedang diedit
                }
            }
        });
        
        tableModel = (DefaultTableModel) tbl1379.getModel();
        muatDataDariFile1379();
    }
    
        private void clearFields() {
        nama1379.setText("");
        nisn1379.setText("");
        asel1379.setText("");
        nilai1379.setText("");
        indexEdit1379 =-1;
    }
        
    private void muatDataDariFile1379() {
    File file = new File("data_siswa.txt");
    if (file.exists()) {
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length == 4) {
                    String nama = data[0];
                    String nisn = data[1];
                    String asal = data[2];
                    int nilai = Integer.parseInt(data[3]);

                    Siswa1379 siswa = new Siswa1379(nama, nisn, asal, nilai);
                    daftarSiswa1379.add(siswa);
                    tableModel.addRow(new Object[]{nama, nisn, asal, nilai});
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nama1379 = new javax.swing.JTextField();
        nisn1379 = new javax.swing.JTextField();
        asel1379 = new javax.swing.JTextField();
        nilai1379 = new javax.swing.JTextField();
        hitunglls1379 = new javax.swing.JButton();
        urtkn1379 = new javax.swing.JButton();
        tmbh1379 = new javax.swing.JButton();
        hps1379 = new javax.swing.JButton();
        smpn1379 = new javax.swing.JButton();
        klmcari1379 = new javax.swing.JTextField();
        cari1379 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1379 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        edit1379 = new javax.swing.JButton();
        batal1379 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("NAMA");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("ASAL SEKOLAH");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("NISN");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("NILAI");

        nama1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama1379ActionPerformed(evt);
            }
        });

        nisn1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nisn1379ActionPerformed(evt);
            }
        });

        asel1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asel1379ActionPerformed(evt);
            }
        });

        nilai1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilai1379ActionPerformed(evt);
            }
        });

        hitunglls1379.setText("HITUNG LULUS");
        hitunglls1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitunglls1379ActionPerformed(evt);
            }
        });

        urtkn1379.setText("URUTKAN");
        urtkn1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urtkn1379ActionPerformed(evt);
            }
        });

        tmbh1379.setText("TAMBAH");
        tmbh1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbh1379ActionPerformed(evt);
            }
        });

        hps1379.setText("HAPUS");
        hps1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hps1379ActionPerformed(evt);
            }
        });

        smpn1379.setText("SIMPAN");
        smpn1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smpn1379ActionPerformed(evt);
            }
        });

        klmcari1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klmcari1379ActionPerformed(evt);
            }
        });

        cari1379.setText("CARI");
        cari1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1379ActionPerformed(evt);
            }
        });

        tbl1379.setAutoCreateRowSorter(true);
        tbl1379.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAMA", "NISN", "ASAL SEKOLAH", "NILAI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl1379);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setForeground(new java.awt.Color(102, 255, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INPUT DATA SISWA BARU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        edit1379.setText("EDIT");
        edit1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1379ActionPerformed(evt);
            }
        });

        batal1379.setText("BATAL");
        batal1379.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal1379ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(klmcari1379, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari1379)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(urtkn1379)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hitunglls1379)
                        .addGap(193, 193, 193))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nisn1379, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama1379, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nilai1379, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(asel1379, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tmbh1379, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(hps1379, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(smpn1379, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit1379, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(batal1379, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nama1379, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nisn1379, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(asel1379, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nilai1379, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(klmcari1379, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cari1379)
                            .addComponent(urtkn1379)
                            .addComponent(hitunglls1379)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(smpn1379)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hps1379)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tmbh1379)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit1379)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(batal1379)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama1379ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama1379ActionPerformed

    private void nisn1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisn1379ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisn1379ActionPerformed

    private void asel1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asel1379ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asel1379ActionPerformed

    private void nilai1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilai1379ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilai1379ActionPerformed

    private void hps1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hps1379ActionPerformed
        // TODO add your handling code here:
        int row = tbl1379.getSelectedRow();
        if (row >= 0) {
            daftarSiswa1379.remove(row);
            tableModel.removeRow(row);
        }
    }//GEN-LAST:event_hps1379ActionPerformed

    private void klmcari1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klmcari1379ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_klmcari1379ActionPerformed

    private void cari1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1379ActionPerformed
        // TODO add your handling code here:
        String keyword = klmcari1379.getText().toLowerCase();
        tableModel.setRowCount(0);
        for (Siswa1379 s : daftarSiswa1379) {
            if (s.getNama1379().toLowerCase().contains(keyword) || s.getNisn1379().contains(keyword)) {
               tableModel.addRow(new Object[]{s.getNama1379(), s.getNisn1379(), s.getAsal1379(), s.getNilai1379()});
            }
        }
        if (keyword.isEmpty()) {
            for (Siswa1379 s : daftarSiswa1379) {
                tableModel.addRow(new Object[]{s.getNama1379(), s.getNisn1379(), s.getAsal1379(), s.getNilai1379()});
            }
            return;
        }
    }//GEN-LAST:event_cari1379ActionPerformed

    private void tmbh1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbh1379ActionPerformed
        // TODO add your handling code here:
        String nama = nama1379.getText();
        String nisn = nisn1379.getText();
        String asal = asel1379.getText();
        int nilai;
        
        try {
            nilai = Integer.parseInt(nilai1379.getText());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nilai harus berupa angka!");
            return;
        }
        
        Siswa1379 siswa = new Siswa1379(nama, nisn, asal, nilai);
        daftarSiswa1379.add(siswa);
        tableModel.addRow(new Object[]{nama, nisn, asal, nilai});
        clearFields();
        
        if (nama.isEmpty() || nisn.isEmpty() || asal.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
}

    }//GEN-LAST:event_tmbh1379ActionPerformed

    private void smpn1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smpn1379ActionPerformed
        // TODO add your handling code here:
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("data_siswa.txt"))) {
            for (Siswa1379 s : daftarSiswa1379) {
                bw.write(s.getNama1379() + "," + s.getNisn1379() + "," + s.getAsal1379() + "," + s.getNilai1379());
                bw.newLine();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        clearFields();
    }//GEN-LAST:event_smpn1379ActionPerformed

    private void urtkn1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urtkn1379ActionPerformed
        // TODO add your handling code here:
        daftarSiswa1379.sort(Comparator.comparingInt(Siswa1379::getNilai1379).reversed());
        tableModel.setRowCount(0);
        for (Siswa1379 s : daftarSiswa1379) {
            tableModel.addRow(new Object[]{s.getNama1379(), s.getNisn1379(), s.getAsal1379(), s.getNilai1379()});
        }
    }//GEN-LAST:event_urtkn1379ActionPerformed
  
    private void hitunglls1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitunglls1379ActionPerformed
        // TODO add your handling code here:
        new HasilLulus(daftarSiswa1379).setVisible(true);
    }//GEN-LAST:event_hitunglls1379ActionPerformed

    private void edit1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1379ActionPerformed
        // TODO add your handling code here:
        if (indexEdit1379 == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu baris yang ingin diedit!");
            return;
        }
        try {
            String nama = nama1379.getText();
            String nisn = nisn1379.getText();
            String asal = asel1379.getText();
            int nilai = Integer.parseInt(nilai1379.getText());
            
            Siswa1379 s = daftarSiswa1379.get(indexEdit1379);
            s.setNama1379(nama);
            s.setNisn1379(nisn);
            s.setAsal1379(asal);
            s.setNilai1379(nilai);
            
            tableModel.setValueAt(nama, indexEdit1379, 0);
            tableModel.setValueAt(nisn, indexEdit1379, 1);
            tableModel.setValueAt(asal, indexEdit1379, 2);
            tableModel.setValueAt(nilai, indexEdit1379, 3);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diedit!");
            clearFields();
            indexEdit1379 = -1; // Reset agar tidak tertukar edit
        
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nilai harus angka!");
        }
    }//GEN-LAST:event_edit1379ActionPerformed

    private void batal1379ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal1379ActionPerformed
        // TODO add your handling code here:
        clearFields(); // kosongkan input dan batalkan edit
        javax.swing.JOptionPane.showMessageDialog(this, "Edit dibatalkan.");
    }//GEN-LAST:event_batal1379ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(() -> {
        new Aplikasi().setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asel1379;
    private javax.swing.JButton batal1379;
    private javax.swing.JButton cari1379;
    private javax.swing.JButton edit1379;
    private javax.swing.JButton hitunglls1379;
    private javax.swing.JButton hps1379;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField klmcari1379;
    private javax.swing.JTextField nama1379;
    private javax.swing.JTextField nilai1379;
    private javax.swing.JTextField nisn1379;
    private javax.swing.JButton smpn1379;
    private javax.swing.JTable tbl1379;
    private javax.swing.JButton tmbh1379;
    private javax.swing.JButton urtkn1379;
    // End of variables declaration//GEN-END:variables
}
